name: "Workflow of satellite 2"

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        shell: bash
        run: |
          echo "Executing workflow of satellite 2"
      - name: Trigger central repo WF
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: mistra-test
          repo: central-repo
          github_token: ${{ secrets.CENTRAL_REPO_TOKEN }}
          workflow_file_name: main.yaml
